### ISSUE TITLE
Setting paper-button disabled doesn't remove it from tab sequence.

### ISSUE THREAD

**Issue by eugene-anisimov** [PolymerElements/iron-behaviors#58] opened 2016-07-05 18:18 UTC
### Description
Setting paper-button disabled doesn't remove it from tab sequence.

The reason seams to be in iron-control-state.html where tabIndex is set to -1. This works if it's set statically, but this doesn't work when set dynamically. What seems to work in Chrome is to remove the tabIndex attribute from the element.

### Expected outcome

When the button disabled attribute is set, it should be neither clickable nor accessible by tabbing.

### Actual outcome

When put on dialog, the button can be accessed by tabbing, ripple works, can close the dialog. 

### Live Demo
https://jsbin.com/quwadiwula/edit?html,css,js,output

### Steps to reproduce
In the demo:
1. When dialog opens, click on the dialog.
2. When button disables, press tab
3. Press space

### Browsers Affected
- [x] Chrome (v51)

**Comment by notwaldorf** [comment] 2016-07-07 14:27
I don't think I can reproduce this on Chrome -- once the button becomes disabled, tabbing only works between the two inputs

**Comment by eugene-anisimov** [comment] 2016-07-07 17:45
Oh, sorry, that was the wrong demo link. Fixed

**Comment by notwaldorf** [comment] 2016-07-11 18:18
Ah, this looks like a `paper-dialog` issue, actually, because if I do the same thing not in a dialog, it works fine (also, I know `paper-dialog` has some magical code around focusing its items)

/cc @valdrinkoshi

**Comment by valdrinkoshi** [comment] 2016-07-12 23:56
Yes, this is caused by the fact that `iron-overlay-behavior` caches what are the focusable nodes when it gets opened in order to save some query selectors, but this optimization is costing more issues than what is worth, and we are removing it in this PR https://github.com/PolymerElements/iron-overlay-behavior/pull/199
(fixes this, test the same code using the PR branch https://jsbin.com/fixoho/1/edit?html,js,output)

**Comment by notwaldorf** [comment] 2016-07-13 17:29
Closing, as this is not an `iron-behaviors` issue, then :)

**Closed by notwaldorf** 2016-07-13 17:29 UTC
